# Generated by Django 5.2.9 on 2025-12-04 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0002_alter_logmovimentacao_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logmovimentacao',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuariosistema',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='usuariosistema',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='data_admissao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='email',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='funcao',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='rg',
        ),
        migrations.RemoveField(
            model_name='colaborador',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='criado_em',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='norma',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='quantidade_total',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='tamanho',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='validade',
        ),
        migrations.AddField(
            model_name='epi',
            name='ca',
            field=models.CharField(default='DESCONHECIDO', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='epi',
            name='nome',
            field=models.CharField(default='DESCONHECIDO', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='cpf',
            field=models.CharField(default='DESCONHECIDO', max_length=14, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='nome',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='colaborador',
            name='setor',
            field=models.CharField(default='DESCONHECIDO', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('data_entrega', models.DateField(auto_now_add=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.colaborador')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colaboradores.epi')),
            ],
        ),
        migrations.DeleteModel(
            name='Emprestimo',
        ),
        migrations.DeleteModel(
            name='LogMovimentacao',
        ),
        migrations.DeleteModel(
            name='UsuarioSistema',
        ),
    ]
