# Generated by Django 5.2.9 on 2025-12-05 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colaboradores', '0003_remove_logmovimentacao_usuario_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EntregaEPI',
        ),
        migrations.DeleteModel(
            name='EPI',
        ),
    ]
