# Generated by Django 5.2.8 on 2025-12-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epi',
            name='descricao',
            field=models.TextField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epi',
            name='quantidade',
            field=models.IntegerField(default=0),
        ),
    ]
