# Generated by Django 5.2.9 on 2025-12-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0002_alter_epi_descricao_alter_epi_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='epi',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='epi',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='epi',
            name='ca',
            field=models.CharField(default='DESCONHECIDO', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epi',
            name='nome',
            field=models.CharField(max_length=200),
        ),
    ]
