# Generated by Django 5.2.9 on 2025-12-05 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epis', '0003_remove_epi_descricao_remove_epi_quantidade_epi_ca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('matricula', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
